version: '3.8'

services:
  # Frontend service
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80

  # Backend services
  backend_1:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/imho
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  backend_2:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/imho
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  # NGINX Load Balancer
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - backend_1
      - backend_2

  # PostgreSQL Database
  database:
    image: postgres
    environment:
      POSTGRES_DB: imho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

volumes:
  angularngixvolume:
