version: '3.8'
services:
  backend:
    image: image-holder-backend
    ports:
      - "8080:8080"
    depends_on:
      - imho
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://imho:5432/imho
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  imho:
    image: postgres
    environment:
      POSTGRES_DB: imho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
